import Subsp.multi.kuma.Main

/-! The usual order `<` on the fixed-dimension OT terms `DOT d` is well-founded, and on them it
coincides with the order generated by natural fundamental-sequence steps (the `multi` version of
`Subsp/Support/OTOrder.lean`). The fundamental sequences use the numerals `ofNatD d n` of the
fixed dimension, so that all intermediate terms stay in dimension `d`. -/

namespace kumakuma.OTOrder

open multi OCF.Jaeger kumakuma.OTQuotient kumakuma.GeneralImageEmbedding
open kumakuma.DimensionCut kumakuma.SourceFundOrder kumakuma.CountableSource

universe u

/-! ### Well-foundedness -/

theorem lt_iff_classLT {d : Nat} (s t : OTD d) :
    s.val < t.val ↔ ClassLT (classOf ⟨d, s⟩) (classOf ⟨d, t⟩) := by
  show compareT s.val t.val = .lt ↔ compareCode (code s.val) (code t.val) = .lt
  rw [compareCode_code]

theorem classLT_wellFounded : WellFounded ClassLT := by
  have h := kumakuma.GeneralImageUniformMain.global_certificate
  refine Subrelation.wf
    (r := InvImage (fun a b : {t : Term // Term.wf t = true} => Term.lt a.1 b.1 = true)
      (fun q => ⟨classConversion q, h.wf q⟩)) ?_
    (InvImage.wf _ OCF.Jaeger.Term.lt_wellFounded)
  intro q r hqr
  exact (h.order q r).mp hqr

/-- The usual order on `OTD d` is well-founded. -/
theorem ot_lt_wellFounded (d : Nat) :
    WellFounded (fun s t : OTD d => s.val < t.val) :=
  Subrelation.wf (fun h => (lt_iff_classLT _ _).mp h)
    (InvImage.wf (fun s : OTD d => classOf ⟨d, s⟩) classLT_wellFounded)

/-! ### Vectors and sizes -/

theorem size_set (v : V multi.T) (i : Nat) (a : multi.T) (hi : i < v.length) :
    V.size (V.set v i a) + (V.get0 v i).size = V.size v + a.size := by
  induction v with
  | emp => exact absurd hi (Nat.not_lt_zero _)
  | snoc b bx ih =>
    have hi' : i < bx.length + 1 := hi
    show V.size (if i = bx.length then V.snoc a bx else V.snoc b (V.set bx i a)) +
      (if i = bx.length then b else V.get0 bx i).size = V.size (V.snoc b bx) + a.size
    by_cases h : i = bx.length
    · rw [ite_eq_left h, ite_eq_left h]; simp only [V.size]; omega
    · rw [ite_eq_right h, ite_eq_right h]
      have := ih (by omega)
      simp only [V.size]; omega

theorem size_pos {s : multi.T} (h : s ≠ .Z) : 0 < s.size := by
  cases s with
  | Z => exact absurd rfl h
  | P xs b => simp only [multi.T.size]; omega

theorem size_set_zero_lt (xs : V multi.T) (i : Nat) (hi : i < xs.length) (hc : V.get0 xs i ≠ .Z) :
    (multi.T.P (V.set xs i .Z) .Z).size < (multi.T.P xs .Z).size := by
  have h1 := size_set xs i .Z hi
  have h2 := size_pos hc
  simp only [multi.T.size] at h1 ⊢
  omega

theorem mul_one (d : Nat) (xs : V multi.T) :
    multi.T.mul (.P xs .Z) (ofNatD d 1) = .P xs .Z := rfl

theorem mul_succ (d : Nat) (xs : V multi.T) (n : Nat) :
    multi.T.mul (.P xs .Z) (ofNatD d (n + 1)) = .P xs (multi.T.mul (.P xs .Z) (ofNatD d n)) := rfl

theorem fund_ofNatD_succ (d n : Nat) (t : multi.T) : T.fund (ofNatD d (n + 1)) t = ofNatD d n := by
  induction n with
  | zero => exact fund_none (fnz_zeros d) t
  | succ n ih =>
    show T.fund (.P (zeros d) (ofNatD d (n + 1))) t = .P (zeros d) (ofNatD d n)
    rw [fund_tail (zeros d) (by intro h; cases h) t, ih]

/-! ### Reachability by steps that lift through contexts -/

/-- A step `u ↦ u[n]` from a nonzero `u` that uses index `0` unless `dom u = ω`. -/
def GoodStep (d : Nat) (u v : multi.T) : Prop :=
  u ≠ .Z ∧ (v = T.fund u .Z ∨ (domF u = .omega ∧ ∃ n : Nat, v = T.fund u (ofNatD d n)))

inductive Reach (d : Nat) : multi.T → multi.T → Prop
  | refl (u : multi.T) : Reach d u u
  | tail {u v w : multi.T} : Reach d u v → GoodStep d v w → Reach d u w

theorem Reach.single {d : Nat} {u v : multi.T} (h : GoodStep d u v) : Reach d u v :=
  .tail (.refl u) h

theorem Reach.trans {d : Nat} {u v w : multi.T} (h₁ : Reach d u v) (h₂ : Reach d v w) :
    Reach d u w := by
  induction h₂ with
  | refl => exact h₁
  | tail _ hs ih => exact .tail ih hs

theorem Reach.lift_tail {d : Nat} (xs : V multi.T) {e e' : multi.T} (h : Reach d e e') :
    Reach d (.P xs e) (.P xs e') := by
  induction h with
  | refl => exact .refl _
  | @tail v w _ hs ih =>
    obtain ⟨hv, hw⟩ := hs
    refine .tail ih ⟨(by intro h; cases h), ?_⟩
    rcases hw with rfl | ⟨hd, n, rfl⟩
    · exact Or.inl (fund_tail xs hv .Z).symm
    · exact Or.inr ⟨(domF_tail xs hv).trans hd, n, (fund_tail xs hv _).symm⟩

theorem lift_step {d : Nat} (xs : V multi.T) (i : Nat) (hil : i < xs.length)
    (hlow : ∀ j, j < i → V.get0 xs j = .Z) {v w : multi.T} (hs : GoodStep d v w) :
    Reach d (.P (V.set xs i v) .Z) (.P (V.set xs i w) .Z) := by
  obtain ⟨hv, hw⟩ := hs
  have hidx : V.get0 (V.set xs i v) i = v := V.get0_set_same xs i v hil
  have hf : V.fnz (V.set xs i v) = some i :=
    fnz_eq_some (by rw [hidx]; exact hv) (fun j hj => by rw [V.get0_set_ne xs i v j (by omega)]; exact hlow j hj)
  have hne : (multi.T.P (V.set xs i v) .Z) ≠ .Z := by intro h; cases h
  have hzero : domF v ≠ .omega → w = T.fund v .Z := by
    intro hd
    rcases hw with h | ⟨h, _⟩
    · exact h
    · exact absurd h hd
  cases hd : domF v with
  | zero => exact absurd ((domF_eq_zero_iff v).mp hd) hv
  | one =>
    rw [hzero (by rw [hd]; intro h; cases h)]
    have hd' : domF (V.get0 (V.set xs i v) i) = .one := by rw [hidx]; exact hd
    cases i with
    | zero =>
      refine Reach.single ⟨hne, Or.inr ⟨domF_one_zero hf hd', 1, ?_⟩⟩
      rw [fund_one_zero hf hd', hidx, set_set, mul_one]
    | succ m =>
      refine Reach.single ⟨hne, Or.inl ?_⟩
      rw [fund_one_succ hf hd', hidx, set_set]
      congr 1
      symm
      apply set_eq_self
      rw [V.get0_set_ne xs _ _ m (by omega)]
      exact hlow m (by omega)
  | omega =>
    have hd' : domF (V.get0 (V.set xs i v) i) = .omega := by rw [hidx]; exact hd
    have key : ∀ t, T.fund (multi.T.P (V.set xs i v) .Z) t = .P (V.set xs i (T.fund v t)) .Z := by
      intro t; rw [fund_omega hf hd' t, hidx, set_set]
    rcases hw with rfl | ⟨_, n, rfl⟩
    · exact Reach.single ⟨hne, Or.inl (key _).symm⟩
    · exact Reach.single ⟨hne, Or.inr ⟨domF_omega hf hd', n, (key _).symm⟩⟩
  | Omega q =>
    rw [hzero (by rw [hd]; intro h; cases h)]
    have hd' : domF (V.get0 (V.set xs i v) i) = .Omega q := by rw [hidx]; exact hd
    refine Reach.single ⟨hne, Or.inl ?_⟩
    by_cases hq : V.set xs i v < q
    · rw [fund_diag hf hd' hq, hidx, set_set]
      rfl
    · rw [fund_nondiag hf hd' hq, hidx, set_set]

/-- Steps of the selected coordinate lift to steps of the principal term. -/
theorem Reach.lift_coord {d : Nat} (xs : V multi.T) (i : Nat) (hil : i < xs.length)
    (hlow : ∀ j, j < i → V.get0 xs j = .Z) {w w' : multi.T} (h : Reach d w w') :
    Reach d (.P (V.set xs i w) .Z) (.P (V.set xs i w') .Z) := by
  induction h with
  | refl => exact .refl _
  | tail _ hs ih => exact ih.trans (lift_step xs i hil hlow hs)

/-- Every term reaches `0`. -/
theorem reach_zero {d : Nat} : ∀ u : multi.T, Reach d u .Z
  | .Z => .refl _
  | .P xs .Z => by
    rcases hm : V.fnz xs with _ | i
    · exact Reach.single ⟨(by intro h; cases h), Or.inl (fund_none hm _).symm⟩
    · have hil := fnz_lt_length hm
      have hc := (V.fnz_some_spec xs i hm).1
      have hlow := (V.fnz_some_spec xs i hm).2
      have h1 := Reach.lift_coord (d := d) xs i hil hlow (reach_zero (V.get0 xs i))
      rw [set_eq_self xs i _ rfl] at h1
      exact h1.trans (reach_zero (.P (V.set xs i .Z) .Z))
  | .P xs (.P ys c) =>
    (Reach.lift_tail xs (reach_zero (.P ys c))).trans (reach_zero (.P xs .Z))
termination_by u => u.size
decreasing_by
  all_goals first
    | exact multi.T.size_get0_lt_P _ _ _
    | exact size_set_zero_lt xs i (by assumption) (by assumption)
    | exact multi.T.size_lt_P_right _ _
    | (simp only [multi.T.size]; omega)

/-- At an uncountable domain, reachability of arguments lifts to the fundamental sequence. -/
theorem reach_arg {d : Nat} : ∀ (c : multi.T) (q : V multi.T), domF c = .Omega q →
    ∀ x y : multi.T, Reach d x y → Reach d (T.fund c x) (T.fund c y)
  | .Z, q, hd, _, _, _ => by rw [domF_Z] at hd; cases hd
  | .P xs b, q, hd, x, y, hxy => by
    by_cases hb : b = .Z
    · subst hb
      rcases hm : V.fnz xs with _ | i
      · rw [domF_none hm] at hd; cases hd
      · have hil := fnz_lt_length hm
        have hlow := (V.fnz_some_spec xs i hm).2
        cases hcd : domF (V.get0 xs i) with
        | zero => rw [domF_zero hm hcd] at hd; cases hd
        | one =>
          cases i with
          | zero => rw [domF_one_zero hm hcd] at hd; cases hd
          | succ m =>
            rw [fund_one_succ hm hcd x, fund_one_succ hm hcd y]
            refine Reach.lift_coord _ m (by rw [V.length_set]; omega) ?_ hxy
            intro j hj
            rw [V.get0_set_ne xs _ _ j (by omega)]
            exact hlow j (by omega)
        | omega => rw [domF_omega hm hcd] at hd; cases hd
        | Omega q' =>
          by_cases hq : xs < q'
          · rw [domF_diag hm hcd hq] at hd; cases hd
          · rw [fund_nondiag hm hcd hq x, fund_nondiag hm hcd hq y]
            exact Reach.lift_coord xs i hil hlow (reach_arg (V.get0 xs i) q' hcd x y hxy)
    · rw [fund_tail xs hb x, fund_tail xs hb y]
      exact Reach.lift_tail xs (reach_arg b q (by rwa [domF_tail xs hb] at hd) x y hxy)
termination_by c => c.size
decreasing_by
  all_goals first
    | exact multi.T.size_get0_lt_P _ _ _
    | exact multi.T.size_lt_P_right _ _

theorem reach_ofNat_succ (d n : Nat) : Reach d (ofNatD d (n + 1)) (ofNatD d n) :=
  Reach.single ⟨ofNatD_succ_ne d n, Or.inl (fund_ofNatD_succ d n .Z).symm⟩

theorem reach_iter {d : Nat} (c : multi.T) (q : V multi.T) (hd : domF c = .Omega q) (n : Nat) :
    Reach d (T.fund c (multi.T.iter (T.fund c) (ofNatD d (n + 1))))
      (T.fund c (multi.T.iter (T.fund c) (ofNatD d n))) := by
  have key : ∀ n, Reach d (multi.T.iter (T.fund c) (ofNatD d (n + 1)))
      (multi.T.iter (T.fund c) (ofNatD d n)) := by
    intro n
    induction n with
    | zero => exact reach_zero _
    | succ n ih =>
      rw [kumakuma.SourceFundOrder.iter_ofNat_succ _ d (n + 1),
        kumakuma.SourceFundOrder.iter_ofNat_succ _ d n]
      exact reach_arg c q hd _ _ ih
  exact reach_arg c q hd _ _ (key n)

theorem reach_mul {d : Nat} (ys : V multi.T) (n : Nat) :
    Reach d (.P ys (multi.T.mul (.P ys .Z) (ofNatD d n))) (multi.T.mul (.P ys .Z) (ofNatD d n)) := by
  induction n with
  | zero => exact reach_zero _
  | succ n ih => rw [mul_succ]; exact Reach.lift_tail ys ih

/-- The chain property: `u[n + 1]` reaches `u[n]`. -/
theorem reach_fund_succ {d : Nat} : ∀ (u : multi.T) (n : Nat),
    Reach d (T.fund u (ofNatD d (n + 1))) (T.fund u (ofNatD d n))
  | .Z, n => by rw [fund_Z, fund_Z]; exact .refl _
  | .P xs b, n => by
    by_cases hb : b = .Z
    · subst hb
      rcases hm : V.fnz xs with _ | i
      · rw [fund_none hm, fund_none hm]; exact .refl _
      · have hil := fnz_lt_length hm
        have hlow := (V.fnz_some_spec xs i hm).2
        have hc0 := (V.fnz_some_spec xs i hm).1
        cases hcd : domF (V.get0 xs i) with
        | zero => exact absurd ((domF_eq_zero_iff _).1 hcd) hc0
        | one =>
          cases i with
          | zero =>
            rw [fund_one_zero hm hcd, fund_one_zero hm hcd, mul_succ]
            exact reach_mul _ n
          | succ m =>
            rw [fund_one_succ hm hcd, fund_one_succ hm hcd]
            refine Reach.lift_coord _ m (by rw [V.length_set]; omega) ?_ (reach_ofNat_succ d n)
            intro j hj
            rw [V.get0_set_ne xs _ _ j (by omega)]
            exact hlow j (by omega)
        | omega =>
          rw [fund_omega hm hcd, fund_omega hm hcd]
          exact Reach.lift_coord xs i hil hlow (reach_fund_succ (V.get0 xs i) n)
        | Omega q =>
          by_cases hq : xs < q
          · rw [fund_diag hm hcd hq, fund_diag hm hcd hq]
            exact Reach.lift_coord xs i hil hlow (reach_iter (V.get0 xs i) q hcd n)
          · rw [fund_nondiag hm hcd hq, fund_nondiag hm hcd hq]
            exact Reach.lift_coord xs i hil hlow
              (reach_arg (V.get0 xs i) q hcd _ _ (reach_ofNat_succ d n))
    · rw [fund_tail xs hb, fund_tail xs hb]
      exact Reach.lift_tail xs (reach_fund_succ b n)
termination_by u => u.size
decreasing_by
  all_goals first
    | exact multi.T.size_get0_lt_P _ _ _
    | exact multi.T.size_lt_P_right _ _

theorem reach_fund_le {d : Nat} (u : multi.T) {a b : Nat} (h : a ≤ b) :
    Reach d (T.fund u (ofNatD d b)) (T.fund u (ofNatD d a)) := by
  induction b with
  | zero => rw [Nat.le_zero.mp h]; exact .refl _
  | succ b ih =>
    rcases Nat.lt_or_ge a (b + 1) with hlt | hge
    · exact (reach_fund_succ u b).trans (ih (by omega))
    · rw [Nat.le_antisymm h hge]; exact .refl _

/-! ### The order generated by fundamental-sequence steps -/

/-- One natural fundamental-sequence step in dimension `d`: `a = b[n]` for a nonzero `b`. -/
def FundStep (d : Nat) (a b : multi.T) : Prop := b ≠ .Z ∧ ∃ n : Nat, a = T.fund b (ofNatD d n)

/-- The order generated from `FundStep` by `FundOrder.TransClosure`. -/
def FundLT (d : Nat) (s t : multi.T) : Prop := FundOrder.TransClosure (FundStep d) s t

theorem fundLT_lt {d : Nat} {s t : multi.T} (h : FundLT d s t) : s < t := by
  induction h with
  | single h => obtain ⟨hb, n, rfl⟩ := h; exact fund_lt _ _ hb
  | tail _ h ih => obtain ⟨hb, n, rfl⟩ := h; exact T.lt_trans ih (fund_lt _ _ hb)

/-- Descent by arbitrary natural steps (`u` reaches `v`). -/
inductive Desc (d : Nat) : multi.T → multi.T → Prop
  | refl (u : multi.T) : Desc d u u
  | step {u v : multi.T} (n : Nat) : u ≠ .Z → Desc d (T.fund u (ofNatD d n)) v → Desc d u v

theorem Desc.trans {d : Nat} {u v w : multi.T} (h₁ : Desc d u v) (h₂ : Desc d v w) :
    Desc d u w := by
  induction h₁ with
  | refl => exact h₂
  | step n hu _ ih => exact .step n hu (ih h₂)

theorem Desc.tail {d : Nat} {u v : multi.T} (h : Desc d u v) (hv : v ≠ .Z) (n : Nat) :
    Desc d u (T.fund v (ofNatD d n)) :=
  h.trans (.step n hv (.refl _))

theorem Reach.desc {d : Nat} {u v : multi.T} (h : Reach d u v) : Desc d u v := by
  induction h with
  | refl => exact .refl _
  | tail _ hs ih =>
    obtain ⟨hv, hw⟩ := hs
    rcases hw with rfl | ⟨_, n, rfl⟩
    · exact ih.tail hv 0
    · exact ih.tail hv n

theorem Desc.fundLT {d : Nat} {u v : multi.T} (h : Desc d u v) : u = v ∨ FundLT d v u := by
  induction h with
  | refl => exact Or.inl rfl
  | step n hu _ ih =>
    have hs : FundStep d (T.fund _ (ofNatD d n)) _ := ⟨hu, n, rfl⟩
    rcases ih with he | h
    · rw [← he]; exact Or.inr (.single hs)
    · exact Or.inr (.tail h hs)

/-! ### Generators of OT -/

/-- The generators of `DOT d`. -/
def base : (d : Nat) → Nat → multi.T
  | 0, n => towerD 0 n
  | lam + 1, n => baseD lam n

theorem base_isOT (d n : Nat) : DOT d (base d n) := by
  cases d with
  | zero => exact .base_0 n
  | succ lam => exact .base_succ lam n

theorem isOT_from_base {d : Nat} {s : multi.T} (h : DOT d s) : ∃ n, Desc d (base d n) s := by
  induction h with
  | base_0 n => exact ⟨n, .refl _⟩
  | base_succ lam n => exact ⟨n, .refl _⟩
  | step lam s _ k ih =>
    obtain ⟨n, h⟩ := ih
    by_cases hz : s = .Z
    · subst hz; exact ⟨n, by rw [fund_Z]; exact h⟩
    · exact ⟨n, h.tail hz k⟩

theorem reach_LF {e : Nat} (d n : Nat) : Reach e (towerD d (n + 1)) (towerD d n) := by
  cases d with
  | zero =>
    induction n with
    | zero =>
      refine Reach.single ⟨(by intro h; cases h), Or.inl ?_⟩
      show multi.T.Z = T.fund (.P .emp .Z) .Z
      rw [fund_none rfl]
    | succ n ih =>
      have h := Reach.lift_tail .emp ih
      exact h
  | succ l =>
    have hlow : ∀ j, j < l → V.get0 (lastVec l .Z) j = .Z :=
      fun j _ => by rw [get0_lastVec]; split <;> rfl
    have hLF : ∀ m, towerD (l + 1) (m + 1) = .P (V.set (lastVec l .Z) l (towerD (l + 1) m)) .Z := by
      intro m
      rw [LF_step, kumakuma.SourceOmegaHighest.lastVec_replace_last]
    induction n with
    | zero =>
      rw [hLF]
      refine Reach.single ⟨(by intro h; cases h), Or.inl ?_⟩
      show multi.T.Z = T.fund (.P (V.set (lastVec l .Z) l .Z) .Z) .Z
      rw [fund_none]
      apply fnz_eq_none
      intro j
      rw [kumakuma.SourceOmegaHighest.lastVec_replace_last, get0_lastVec]
      split <;> rfl
    | succ n ih =>
      have h := Reach.lift_coord (lastVec l .Z) l (by rw [lastVec_length]; omega) hlow ih
      rw [← hLF (n + 1), ← hLF n] at h
      exact h

theorem reach_base (d n : Nat) : Reach d (base d (n + 1)) (base d n) := by
  cases d with
  | zero => exact reach_LF 0 n
  | succ l =>
    have h := Reach.lift_coord (d := l + 1) (lowVec l .Z) 0 (by rw [lowVec_length]; omega)
      (fun j hj => absurd hj (Nat.not_lt_zero j)) (reach_LF (l + 1) n)
    rw [lowVec_set_zero, lowVec_set_zero] at h
    exact h

theorem desc_base {d : Nat} {n N : Nat} (h : n ≤ N) : Desc d (base d N) (base d n) := by
  induction N with
  | zero => rw [Nat.le_zero.mp h]; exact .refl _
  | succ N ih =>
    rcases Nat.lt_or_ge n (N + 1) with hlt | hge
    · exact (reach_base d N).desc.trans (ih (by omega))
    · rw [Nat.le_antisymm h hge]; exact .refl _

/-! ### Main results -/

/-- Everything reachable from an OT element is linearly ordered by reachability. -/
theorem desc_total {d : Nat} (u : OTD d) :
    ∀ x y : multi.T, Desc d u.val x → Desc d u.val y → Desc d x y ∨ Desc d y x := by
  refine (ot_lt_wellFounded d).induction
    (C := fun u : OTD d => ∀ x y : multi.T, Desc d u.val x → Desc d u.val y →
      Desc d x y ∨ Desc d y x) u ?_
  intro ⟨uv, huv⟩ ih x y hx hy
  cases hx with
  | refl => exact Or.inl hy
  | step a hu hx' =>
    cases hy with
    | refl => exact Or.inr (.step a hu hx')
    | step b _ hy' =>
      rcases Nat.le_total a b with hab | hba
      · exact ih ⟨_, .step _ _ huv b⟩ (fund_lt _ _ hu) x y
          ((reach_fund_le uv hab).desc.trans hx') hy'
      · exact ih ⟨_, .step _ _ huv a⟩ (fund_lt _ _ hu) x y hx'
          ((reach_fund_le uv hba).desc.trans hy')

/-- On `DOT d`, the usual order coincides with the order generated by natural
fundamental-sequence steps. -/
theorem lt_iff_fundLT {d : Nat} {s t : multi.T}
    (hs : DOT d s) (ht : DOT d t) : s < t ↔ FundLT d s t := by
  refine ⟨fun hlt => ?_, fundLT_lt⟩
  obtain ⟨n₁, h₁⟩ := isOT_from_base hs
  obtain ⟨n₂, h₂⟩ := isOT_from_base ht
  have hs' := (desc_base (d := d) (Nat.le_max_left n₁ n₂)).trans h₁
  have ht' := (desc_base (d := d) (Nat.le_max_right n₁ n₂)).trans h₂
  rcases desc_total ⟨_, base_isOT d (max n₁ n₂)⟩ s t hs' ht' with h | h
  · rcases h.fundLT with he | h'
    · subst he; exact absurd hlt (T.lt_irrefl _)
    · exact absurd (T.lt_trans hlt (fundLT_lt h')) (T.lt_irrefl _)
  · rcases h.fundLT with he | h'
    · subst he; exact absurd hlt (T.lt_irrefl _)
    · exact h'

/-- The fundamental-sequence order is well-founded on `DOT d`. -/
theorem fundLT_wellFounded (d : Nat) :
    WellFounded (fun s t : OTD d => FundLT d s.val t.val) :=
  Subrelation.wf (fun h => fundLT_lt h) (ot_lt_wellFounded d)

end kumakuma.OTOrder
