import Subsp.multi.kuma.OTOrder
import Subsp.multi.kuma.nt

/-! Main results for the `multi` kumakuma system, under the large-cardinal hypothesis:

* `kumakuma.NOT_order_embedding`: an order embedding of `kumakuma.sys.NOT` into the well-formed
  OCF notations below `Ω` (and `kumakuma.NOT_ordinal_embedding` into the OCF ordinals);
* `kumakuma.NOT_lt_wellFounded`: the order `<` on `kumakuma.sys.NOT` is well-founded;
* `kumakuma.NOTFundLt_iff_lt`: the order generated by fundamental-sequence steps coincides with
  `<`, and `kumakuma.NOTFundLt_wellFounded`: it is well-founded.

This is an order *embedding* (not an isomorphism). Every `NOT` element is matched with an OT term
of a fixed dimension (`DOT d`) having the same normal-form code; the classes of such terms are
converted to OCF notations by `classConversion`, and `global_certificate` shows that this
conversion is well-formed and order preserving. -/

open multi

namespace kumakuma.Stop

open OCF.Jaeger kumakuma.OTQuotient kumakuma.GeneralImageEmbedding kumakuma.CountableSource
open kumakuma.FirstLimit kumakuma.FiniteCorrespondence

universe u v

/-! ### Matching the bases of `kumakuma.sys` with fixed-dimension OT terms -/

theorem get0_LF (k i : Nat) :
    V.get0 (kumakuma.T.LF (k + 1)) i = if i = k + 1 then multi.T.ofNat 1 else .Z := by
  induction k generalizing i with
  | zero =>
    show (if i = (V.snoc multi.T.Z V.emp).length then multi.T.ofNat 1
      else V.get0 (.snoc .Z .emp) i) = _
    have hl : (V.snoc multi.T.Z V.emp).length = 1 := rfl
    rw [hl]
    by_cases h1 : i = 1
    · rw [ite_eq_left h1, ite_eq_left (by omega)]
    · rw [ite_eq_right h1, ite_eq_right (by omega)]
      show (if i = 0 then multi.T.Z else V.get0 V.emp i) = _
      split <;> rfl
  | succ k ih =>
    show V.get0 (V.append (kumakuma.T.LF (k + 1)) (.snoc .Z .emp)) i = _
    rw [V.get0_append]
    have hl : (V.snoc multi.T.Z V.emp).length = 1 := rfl
    rw [hl]
    by_cases hi : i < 1
    · rw [ite_eq_left hi, ite_eq_right (by omega)]
      show (if i = 0 then multi.T.Z else V.get0 V.emp i) = _
      split <;> rfl
    · rw [ite_eq_right hi, ih]
      by_cases h : i = k + 1 + 1
      · rw [ite_eq_left (by omega), ite_eq_left h]
      · rw [ite_eq_right (by omega), ite_eq_right h]

theorem code_LF_top (k : Nat) :
    code (multi.T.P (kumakuma.T.LF (k + 1)) .Z) = code (dimensionTop k) := by
  show code (multi.T.P (kumakuma.T.LF (k + 1)) .Z) =
    code (multi.T.P (lastVec (k + 1) (ofNatD (k + 2) 1)) .Z)
  apply kumakuma.OTQuotient.code_P_congr _ rfl
  intro i
  rw [get0_LF, get0_lastVec]
  by_cases h : i = k + 1
  · rw [ite_eq_left h, ite_eq_left h, code_ofNat, code_ofNatD]
  · rw [ite_eq_right h, ite_eq_right h]

theorem code_base_succ (k : Nat) : code (sys.base (k + 1)) = code (dimensionBound k) := by
  show code (multi.T.P (.snoc (multi.T.P (kumakuma.T.LF (k + 1)) .Z) .emp) .Z) =
    code (multi.T.P (lowVec (k + 1) (dimensionTop k)) .Z)
  apply kumakuma.OTQuotient.code_P_congr _ rfl
  intro i
  rw [get0_lowVec]
  show code (if i = 0 then multi.T.P (kumakuma.T.LF (k + 1)) .Z else V.get0 V.emp i) = _
  by_cases h : i = 0
  · rw [ite_eq_left h, ite_eq_left h]; exact code_LF_top k
  · rw [ite_eq_right h, ite_eq_right h]; rfl

theorem code_base_zero : code (sys.base 0) = code omegaSource := by
  show code (multi.T.P (.snoc (multi.T.P V.emp .Z) .emp) .Z) =
    code (multi.T.P (.snoc (ofNatD 1 1) .emp) .Z)
  have h : code (multi.T.P V.emp .Z) = code (ofNatD 1 1) := by
    rw [code_ofNatD, ← code_ofNat]; rfl
  apply kumakuma.OTQuotient.code_P_congr _ rfl
  intro i
  show code (if i = 0 then multi.T.P V.emp .Z else V.get0 V.emp i) =
    code (if i = 0 then ofNatD 1 1 else V.get0 V.emp i)
  split
  · exact h
  · rfl

/-- Every OT term of `kumakuma.sys` has a fixed-dimension OT witness with the same code. -/
theorem isOT_witness {t : multi.T} (h : sys.IsOT t) : ∃ d s, DOT d s ∧ code s = code t := by
  induction h with
  | base n =>
    cases n with
    | zero => exact ⟨1, omegaSource, omegaSource_isOT, code_base_zero.symm⟩
    | succ k => exact ⟨k + 2, dimensionBound k, dimensionBound_isOT k, (code_base_succ k).symm⟩
  | step s _ n ih =>
    obtain ⟨d, s', hs', hc⟩ := ih
    refine ⟨d, T.fund s' (ofNatD d n), DOT.step d s' hs' n, ?_⟩
    apply (code_eq_iff _ _).2
    exact kumakuma.T.fund_congr _ _ _ _ ((code_eq_iff _ _).1 hc)
      (by rw [norm_ofNatD, multi.T.ofNat_norm])

theorem NOT_witness (a : sys.NOT) : ∃ d s, DOT d s ∧ code s = code a.val.1 := by
  obtain ⟨t, ht, he⟩ := FundSys.NIsOT.exists sys_cong a.2
  obtain ⟨d, s, hs, hc⟩ := isOT_witness ht
  refine ⟨d, s, hs, ?_⟩
  rw [hc, ← he]
  exact (code_norm t).symm

theorem NOT_class (a : sys.NOT) : ∃ q : Classes, classCode q = code a.val.1 := by
  obtain ⟨d, s, hs, hc⟩ := NOT_witness a
  exact ⟨classOf ⟨d, ⟨s, hs⟩⟩, hc⟩

/-- The class of fixed-dimension OT terms matching a `NOT` element. -/
noncomputable def NOTclass (a : sys.NOT) : Classes := Classical.choose (NOT_class a)

theorem NOTclass_code (a : sys.NOT) : classCode (NOTclass a) = code a.val.1 :=
  Classical.choose_spec (NOT_class a)

theorem NOT_lt_iff_classLT (a b : sys.NOT) : a.val < b.val ↔ ClassLT (NOTclass a) (NOTclass b) := by
  show compareT a.val.1 b.val.1 = .lt ↔
    compareCode (classCode (NOTclass a)) (classCode (NOTclass b)) = .lt
  rw [NOTclass_code, NOTclass_code, compareCode_code]

/-- An order on `NOT` reflected into an irreflexive relation forces injectivity. -/
theorem injective_of_lt_iff {α : Type v} (f : sys.NOT → α) (r : α → α → Prop)
    (hirr : ∀ x, ¬ r x x) (h : ∀ a b, a.val < b.val ↔ r (f a) (f b)) :
    ∀ a b, f a = f b → a = b := by
  intro a b he
  rcases NT.lt_trichotomy a.val b.val with hab | hab | hab
  · exact absurd ((h a b).1 hab) (by rw [he]; exact hirr _)
  · exact Subtype.ext hab
  · exact absurd ((h b a).1 hab) (by rw [he]; exact hirr _)

/-- The conversion of a `NOT` element to a well-formed OCF notation below `Ω`. -/
noncomputable def embed [LargeCardinals.{u}] (a : sys.NOT) : WFBelowOmega :=
  ⟨classConversion (NOTclass a),
    (kumakuma.GeneralImageUniformMain.global_certificate.{u}).wf _, class_below _⟩

theorem embed_lt_iff [LargeCardinals.{u}] (a b : sys.NOT) :
    a.val < b.val ↔ Term.lt (embed.{u} a).val (embed.{u} b).val = true := by
  rw [NOT_lt_iff_classLT]
  exact (kumakuma.GeneralImageUniformMain.global_certificate.{u}).order _ _

theorem embed_V_lt_iff [LargeCardinals.{u}] (a b : sys.NOT) :
    a.val < b.val ↔ Term.V.{u} (embed.{u} a).val < Term.V.{u} (embed.{u} b).val := by
  rw [embed_lt_iff]
  exact lt_iff_V.{u} (embed.{u} a).2.1 (embed.{u} b).2.1

end kumakuma.Stop

namespace kumakuma

open OCF.Jaeger kumakuma.Stop kumakuma.OTQuotient kumakuma.GeneralImageEmbedding

universe u

/-- An order embedding of the OT terms of the `multi` kumakuma system into the well-formed OCF
notations below `Ω`. -/
theorem NOT_order_embedding [LargeCardinals.{u}] :
    ∃ f : sys.NOT → WFBelowOmega,
      (∀ s t, f s = f t → s = t) ∧
      (∀ s t, s.val < t.val ↔ Term.lt (f s).val (f t).val = true) :=
  ⟨embed.{u}, injective_of_lt_iff embed.{u} (fun x y => Term.lt x.val y.val = true)
    (fun x => by simp [kumakuma.TargetArithmetic.lt_self]) embed_lt_iff, embed_lt_iff⟩

/-- The same embedding, read in the OCF ordinals. -/
theorem NOT_ordinal_embedding [LargeCardinals.{u}] :
    ∃ f : sys.NOT → OCF.Ordinal.{u},
      (∀ s t, f s = f t → s = t) ∧ (∀ s t, s.val < t.val ↔ f s < f t) :=
  ⟨fun a => Term.V.{u} (embed.{u} a).val,
    injective_of_lt_iff _ (fun x y => x < y) OCF.Ordinal.lt_irrefl embed_V_lt_iff, embed_V_lt_iff⟩

/-- The order `<` on the OT terms of the `multi` kumakuma system is well-founded. -/
theorem NOT_lt_wellFounded [LargeCardinals.{u}] :
    WellFounded (fun a b : sys.NOT => a.val < b.val) :=
  Subrelation.wf (fun h => (NOT_lt_iff_classLT _ _).mp h)
    (InvImage.wf NOTclass kumakuma.OTOrder.classLT_wellFounded.{u})

theorem fundDesc : sys.FundDesc := by
  intro b n hb
  show multi.T.norm (T.fund b.val.1 (multi.T.rep (multi.T.ofNat n)).1) < b.val.1
  have h := (multi.T.lt_norm_iff _ _).1
    (kumakuma.SourceFundOrder.fund_lt b.val.1 (multi.T.rep (multi.T.ofNat n)).1 hb)
  rwa [b.val.2] at h

theorem top_step {r : multi.T → multi.T → Prop} {x c : multi.T} (h : FundOrder.TransClosure r x c) :
    ∃ b, r b c ∧ (x = b ∨ FundOrder.TransClosure r x b) := by
  cases h with
  | single h => exact ⟨_, h, Or.inl rfl⟩
  | tail h hs => exact ⟨_, hs, Or.inr h⟩

theorem fundCofinal [LargeCardinals.{u}] : sys.FundCofinal := by
  intro a b hba
  obtain ⟨da, sa, hsa, hca⟩ := NOT_witness a
  obtain ⟨db, sb, hsb, hcb⟩ := NOT_witness b
  have hsa' := isOT_promote (Nat.le_max_left da db) hsa
  have hsb' := isOT_promote (Nat.le_max_right da db) hsb
  have hca' : code (padTo (max da db) sa) = code a.val.1 := by rw [code_padTo]; exact hca
  have hcb' : code (padTo (max da db) sb) = code b.val.1 := by rw [code_padTo]; exact hcb
  have hlt : padTo (max da db) sb < padTo (max da db) sa := by
    show compareT _ _ = .lt
    rw [← compareCode_code, hca', hcb', compareCode_code]
    exact hba
  have hF := (kumakuma.OTOrder.lt_iff_fundLT.{u} hsb' hsa').mp hlt
  obtain ⟨c, ⟨_, n, hc⟩, hle⟩ := top_step hF
  refine ⟨n, ?_⟩
  have hle' : padTo (max da db) sb ≤ c := by
    rcases hle with he | h
    · rw [he]; exact T.le_of_eqv (compareT_self _)
    · exact T.le_of_lt (kumakuma.OTOrder.fundLT_lt h)
  have hnc : multi.T.norm c = (sys.ntFund a.val (multi.T.rep (multi.T.ofNat n))).1 := by
    show _ = multi.T.norm (T.fund a.val.1 (multi.T.norm (multi.T.ofNat n)))
    rw [hc]
    apply kumakuma.T.fund_congr
    · exact (code_eq_iff _ _).1 hca'
    · rw [norm_ofNatD, multi.T.ofNat_norm, multi.T.ofNat_norm]
  have h1 := (multi.T.le_norm_iff _ _).1 hle'
  rw [(code_eq_iff _ _).1 hcb', b.val.2, hnc] at h1
  exact h1

/-- On the OT terms of the `multi` kumakuma system, the order generated by fundamental-sequence
steps coincides with `<`. -/
theorem NOTFundLt_iff_lt [LargeCardinals.{u}] (a b : sys.NOT) :
    sys.NOTFundLt a b ↔ a.val < b.val :=
  FundSys.NOTFundLt_iff_lt fundDesc fundCofinal.{u} NOT_lt_wellFounded.{u} a b

/-- The fundamental-sequence order on the OT terms of the `multi` kumakuma system is
well-founded. -/
theorem NOTFundLt_wellFounded [LargeCardinals.{u}] : WellFounded sys.NOTFundLt :=
  Subrelation.wf (fun h => FundSys.NOTFundLt_lt fundDesc h) NOT_lt_wellFounded.{u}

end kumakuma
